// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zaodidtockqjpcunbyde.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inphb2RpZHRvY2txanBjdW5ieWRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NTQ4NzQsImV4cCI6MjA2NzUzMDg3NH0.nmyItAuUOixQH3kOiwwNj4XpGSkNLop7iYoSVKEL9Ew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});